name: scipy2021-bioimage-analysis
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- numpy
- scipy
- scikit-image
- scikit-learn
- dask
- zarr
- bokeh
- ipython
- matplotlib
- jupyter
- notebook
- napari
- pandas
- seaborn
- dask-image==0.5.0
- magicgui
- jupyterlab
- pip:
    - jupyter-book
    - ghp-import
